sonar.projectKey=abrahamp7_finanzly
sonar.organization=abrahamp7
sonar.projectName=Finanzly

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.git/**,**/coverage/**

sonar.host.url=https://sonarcloud.io
sonar.token=30061d04f1fe9eac4438de70ae5627075fb49e15
