sonar.projectKey=finanzly
sonar.organization=nicolaslegeds-spec
sonar.projectName=Finanzly

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.git/**,**/coverage/**

sonar.host.url=https://sonarcloud.io
sonar.token=278c9a8299688a8cead39c7964d2949d84abcfbc